### ISSUE TITLE
more error handling for Codebook

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/phonto#10]
cb2 = nhanesCodebook(nh_table = "DEMO_I", colname = c("RIAGENDR", "RIDRETH1")
+ )
Error in new_result(connection@ptr, statement, immediate) :
Expecting a single string value: [type=character; extent=2].

 not sure if we want to handle multiple column names - seems like a good idea - return a named list for example with one entry per column
 - if not, then just test that colname is length 1 and stop if not...

**Comment by ainilaha** [comment]
I have checked nhanesA:: nhanesCodebook(), and it only can not handle multiple column names. So, let's keep aligned with it for now. I have added the error message.
