### ISSUE TITLE
jointQuery/unionQuery

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/phonto#11]
we probably need some mechanism with jointQuery and unionQuery to handle the case where we are merging over two or more of the NHANES surveys - eg we get data from both I and J;
  one way to do that would be to just add another argument to these functions that says include_years=TRUE/FALSE
and then use the helper functions to go from the name (with _I or _J ) to the years?  and add that after pulling
the data back from the db (or maybe this info is in the db?)

**Comment by ainilaha** [comment]
I have added "years" in `unionQuery()` and still thinking about how to add years `jointQuery ()` in an efficient way.

**Comment by ainilaha** [comment]
added the years.
