### ISSUE TITLE
very minor column name comment

### ISSUE THREAD

**Issue by Teresa1207** [ccb-hms/phonto#18]
very minor - columns names for years start and years stop are : `Begin.Year` and `EndYear` , ideally these would be consistent, i.e. either both with the `.` or both without. though this might not be worth the hassle to change.

affected tables: 

```
nhanesTables
nhanesTableVars
nhanesSearchVarName
nhanesSearch
jointQuery
```

**Comment by ainilaha** [comment]
@Teresa1207  I raised the same question before, and Chris explained to us that he keeps that name convention because of that is the CDC website named that way.
