### ISSUE TITLE
nhanesTableVars

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/phonto#2]
currently: 
> nhanesTableVars(nh_table="HDL_D")
       Variable                     Description
1          SEQN                            <NA>
2        LBDHDD  Direct HDL-Cholesterol (mg/dL)
3      LBDHDDSI Direct HDL-Cholesterol (mmol/L)
4   DownloadUrl                            <NA>
5 Questionnaire                            <NA>

  SEQN should report "Respondent sequence number"
 I think Questionnaire should be HDL_D
and the DownloadUrl (probably should be URL, but that is minor) - should either say URL used to download 
or perhaps the design should strip out that last two lines - as they are not NHANES variables, but rather things we have put in to that table for our convenience.

**Comment by rgentlem** [comment]
we see this now:
> nhanesTableVars(nh_table="HDL_D")
  Variable.Name            Variable.Description
1          SEQN      Respondent sequence number
2        LBDHDD  Direct HDL-Cholesterol (mg/dL)
3      LBDHDDSI Direct HDL-Cholesterol (mmol/L)
4   DownloadUrl                            <NA>
5 Questionnaire                            <NA>

and nhanesA gives this:
> nhanesTableVars(nh_table="HDL_D", data_group="LAB")
  Variable.Name            Variable.Description
1        LBDHDD  Direct HDL-Cholesterol (mg/dL)
2      LBDHDDSI Direct HDL-Cholesterol (mmol/L)
3          SEQN     Respondent sequence number.

we are searching in the Questionnaire Variables table, that no longer has DownloadUrl and Questionnaire as columns - can you update the code for nhanesTableVars 
- and perhaps note that this is one instance where we don't need to specify data_group, so maybe we ignore it?
-

**Comment by ainilaha** [comment]
we will add the detail once the DB is updated.
