### ISSUE TITLE
lack of consistency in jointQuery and unionQuery

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/phonto#21]
So this code:
cols = list(DEMO_I=c("RIDAGEYR","RIAGENDR","RIDRETH1","DMDEDUC2"), 
+             DEMO_J=c("RIDAGEYR","RIAGENDR","RIDRETH1","DMDEDUC2"))
dfdf = jointQuery(cols)
 colnames(dfdf)
[1] "SEQN"       "RIDAGEYR"   "RIAGENDR"   "RIDRETH1"   "DMDEDUC2"   "Begin.Year"
[7] "EndYear"   

First problem:
 you should be able to do 
dfdy = unionQuery(cols)
but that is an error, it sure would be nice if these two functions took the same inputs
then when you maneuver it,
> dfdy=unionQuery(names(cols), cols[[1]])
> colnames(dfdy)
[1] "SEQN"     "RIDAGEYR" "RIAGENDR" "RIDRETH1" "DMDEDUC2" "years"   
you do not actually get the same column names - and you should
we are making up the data for either Begin.Year/EndYear or years, but we need to make it up the same way all the time...

things get messed up in the CobaltPaper vignette (Imputation/7_enwas) because of this

also it would be nice to document exactly what either/both of these functions do - the man pages are devoid of details 
and the also don't describe the intention....

**Comment by ainilaha** [comment]
Fixed inconstancy issue and added the objective of the functions.
