### ISSUE TITLE
jointQuery

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/phonto#5]
Hi Laha,
   For both unionQuery and jointQuery I think the user should be able to specify Questionnaire names, not just Nathan's internal table names.  They are all set up as views, as far as I know,  but somehow that didn't seem to work for me
LDLTabs = searchTablesByVar('LBDLDL',ystart="2015", ystop="2018")
##Triglycerides
triglyTabs = searchTablesByVar('LBXTR', ystart="2015", ystop="2018")
##A1C
A1C = searchTablesByVar("LBXGH",ystart="2015", ystop="2018")
##been told by Dr. has diabetes
DrDiab = searchTablesByVar("DIQ010",ystart="2015", ystop="2018")
##HDLTabs
HDLTabs = searchTablesByVar("LBDHDD",ystart="2015", ystop="2018")

questionnaires = unique(c(HDLTabs$Questionnaire, LDLTabs$Questionnaire,
                        A1C$Questionnaire, DrDiab$Questionnaire,
                        triglyTabs$Questionnaire, "DEMO_I", "DEMO_J"))
# find tables with the above functions and joint query like:
#patterns <- c("DemographicVariablesAndSampleWeights","ChromiumAndCobalt","BloodPressureAndCholesterol","BodyMeasures")
cols <- c("RIDAGEYR","RIAGENDR","BMXBMI","RIDRETH1","DMDEDUC2","years",'BPQ050A','BPQ020',"LBDBCOSI","LBXBCO")
base_df <- jointQuery(questionnaires,cols)

**Comment by ainilaha** [comment]
We can do something now

```R
df = jointQuery( list(BPQ_J=c("BPQ020", "BPQ050A"), DEMO_J=c("RIDAGEYR","RIAGENDR")))
cols = list(DEMO_I=c("RIDAGEYR","RIAGENDR","RIDRETH1","DMDEDUC2"),
                     DEMO_J=c("RIDAGEYR","RIAGENDR","RIDRETH1","DMDEDUC2"),
                     BPQ_I=c('BPQ050A','BPQ020'),BPQ_J=c('BPQ050A','BPQ020'),
                     HDL_I=c("LBDHDD"),HDL_J=c("LBDHDD"), TRIGLY_I=c("LBXTR","LBDLDL"),
                     TRIGLY_J=c("LBXTR","LBDLDL"))
ans = jointQuery(cols)
```
