### ISSUE TITLE
nhanesSearchTableNames

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/phonto#6]
Right now we get:
 nhanesSearchTableNames("BMX",details=T)
   Questionnaire    TableName     years
1            BMX BodyMeasures 1999-2000
2          BMX_B BodyMeasures 2001-2002
3          BMX_C BodyMeasures 2003-2004

could you add to that the number of rows in the table (nrow in R parlance)
and I don't know if we have this but there is a table name in the HTML 
Body Measures (BMX_J) 
I think in many cases Nathan has used it to create the TableNames in his DB, but it would be good to have it for every Questionnaire.

**Comment by ainilaha** [comment]
Now we do have the number of rows in the table and we will have the details once we have details in the DB.
```R
> nhanesSearchTableNames("BMX",details=T)
   Questionnaire TableName     years
1            BMX       BMX 1999-2000
2          BMX_B     BMX_B 2001-2002
3          BMX_C     BMX_C 2003-2004
4          BMX_D     BMX_D 2005-2006
5          BMX_E     BMX_E 2007-2008
6          BMX_F     BMX_F 2009-2010
7          BMX_G     BMX_G 2011-2012
8          BMX_H     BMX_H 2013-2014
9          BMX_I     BMX_I 2015-2016
10         BMX_J     BMX_J 2017-2018
```
