### ISSUE TITLE
minor comment: nhanesSearch / nhanesSearchVarName

### ISSUE THREAD

**Issue by Teresa1207** [ccb-hms/phonto#8]
General comment: I think as much as possible it makes sense to have consistency in output across the searching functions. e.g. nhanesSearchVarName provides the column 'years', while nhanesSearch() provides the columns BeginYear, EndYear. 

Another example,  nhanesSearch includes a lot more information (e.g.,  'Description' column) than nhanesSearchVar. It seems simple enough to make these consistent so that the user will not need to run multiple queries + a merge.

**Comment by ainilaha** [comment]
Yes, it is a good one, and we may need to talk to Chris to have consistency in output. We will go through the functions one by one with Chris at some point.
