### ISSUE TITLE
better error handling for nhanesCodebook

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/phonto#9]
The error message isn't that helpful - perhaps we could check to see if colname is a variable in the table given (and perhaps that the table name given is one we have) so that the errors are easier for the user to understand

cb1 = nhanesCodebook(nh_table = "DEMO_I", colname = "RIAGNDR")
Error in phonto::nhanesTranslate(nh_table, colname, details = TRUE)[[1]] : 
  subscript out of bounds
> cb1 = nhanesCodebook(nh_table = "DEMO_I", colname = "RIAGENDR")

**Comment by ainilaha** [comment]
I have revised the function to align with nhanesA:: nhanesCodebook() and added the error messages.
